### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: sun.tools.attach.WindowsAttachProvider.tempPath()Ljava/lang/String;

### ISSUE THREAD

**Issue by kevinsnameneedlong** [veo/vagent#5]
java -jar Agent-1.0-SNAPSHOT-jar-with-dependencies.jar
Exception in thread "main" java.lang.UnsatisfiedLinkError: sun.tools.attach.WindowsAttachProvider.tempPath()Ljava/lang/String;
        at sun.tools.attach.WindowsAttachProvider.tempPath(Native Method)
        at sun.tools.attach.WindowsAttachProvider.isTempPathSecure(WindowsAttachProvider.java:91)
        at sun.tools.attach.WindowsAttachProvider.listVirtualMachines(WindowsAttachProvider.java:75)
        at io.earcam.wrapped.com.sun.tools.attach.Provider.listVirtualMachines(Provider.java:113)
        at com.sun.tools.attach.VirtualMachine.list(VirtualMachine.java:147)
        at org.apache.catalina.servlets.Attach.att(Attach.java:50)
        at org.apache.catalina.servlets.Attach.main(Attach.java:16)

这个报错一直没找到具体原因

**Comment by veo** [comment]
windows一般是都是没有attach.dll或者tools.jar的问题。装完整的jdk可能能解决这个报错

**Comment by FightingLzn9** [comment]
jdk高版本不适配
